version: '1.0.0'

services:
  backend:
    image: backend
    container_name: backend
    restart: unless-stopped
    expose:
      - "8001"
    env_file:
      - .env

  frontend:
    image: frontend
    container_name: frontend
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
