version: '1.0.0'

services:

  backend:
    image: backend
    container_name: backend
    restart: always
    ports:
      - "8000:8001"
    depends_on:
      - redis
      - rabbitmq   # Add RabbitMQ dependency here
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


  rabbitmq:
    image: rabbitmq:3-management  # RabbitMQ with management plugin UI included
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # AMQP protocol port (your app connects here)
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest   # You can change these credentials
      RABBITMQ_DEFAULT_PASS: guest
