from docx import Document

# Create a new document
doc = Document()
doc.add_heading('My Document Title', level=1)
doc.add_paragraph('Hello world! This is a DOCX generated by Python.')

para = doc.add_paragraph()
run = para.add_run('This text is bold and italic. ')
run.bold = True
run.italic = True
# Save to file
doc.save('my_document.docx')
