from enum import Enum


class Tables(str, Enum):
    ENTITIES = "entities"
    ORGANIZATIONS  = "organizations"
    MODULES = "modules"
    ENGAGEMENTS = "engagements"
    ANNUAL_PLANS = "annual_plans"
    USERS  = "users"
    ORGANIZATIONS_USERS = "organizations_users"
    MODULES_USERS = "modules_users"
    ACTIVATIONS = "activations"
    AUDIT_LICENCES = "audit_licences"
    MAIN_PROGRAM = "main_program"
    SUB_PROGRAM = "sub_program"
    ENGAGEMENT_STAFF = "staff"
    ENGAGEMENT_PROFILE = "profile"
    ISSUES = "issue"
    ISSUE_ACTORS = "issue_actors"
    ISSUE_RESPONSES = "implementation_details"
    RISK_CONTROL = "PRCM"
    LIBRARY = "library"
    FOLLOW_UP = "follow_up"
    FOLLOW_UP_TESTS = "follow_up_tests"
    FOLLOW_ENGAGEMENTS = "follow_up_engagements"
    FOLLOW_ISSUES = "follow_up_issues"
    ATTACHMENTS = "attachments"
    RECENT_ACTIVITIES = "recent_activities"
    NOTIFICATIONS = "notifications"
    MANAGEMENT = "managers"
    POLICIES = "policies"
    REGULATIONS = "regulations"
    ENGAGEMENT_PROCESS = "engagement_process"
    REPORTS = "reports"
    BUSINESS_CONTACT = "business_contact"
    ROLES = "roles"


