name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "eauditrisk.com"
          username: "ubuntu"
          key: ${{ secrets.KEY }}
          script: |
            cd project/Samwel
            git pull
            docker build --no-cache -t backend .
            IMAGE_NAME="kijani:tag"
            CONTAINERS=$(docker ps -q --filter ancestor=$IMAGE_NAME)
            if [ -n "$CONTAINERS" ]; then
              echo "Stopping containers: $CONTAINERS"
              docker stop $CONTAINERS
            else
              echo "No containers running with image $IMAGE_NAME"
            fi
            
            docker run -d -p 3000:3000 kijani
