name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "eauditrisk.com"
          username: "ubuntu"
          key: ${{ secrets.KEY }}
          script: |
            cd project/Samwel
            git pull
            docker build -t backend .
            docker builder prune -f  
            sudo docker compose down
            sudo docker compose up -d
            sudo systemctl stop backend.service
            sudo systemctl start backend.service
